import 'package:town_square/features/activity_screen/model/activity_model.dart';

List<ActivityModel> activityList = [
  ActivityModel(
    activityName: "Beach Yoga",
    time: "08:00",
    duration: "60 min",
    location: "La Playa de la Rada",
    spots: 8,
    intensity: "light",
    price: "9€",
    category: "creative",
    joined: false,
  ),
  ActivityModel(
    activityName: "Reformer Pilates",
    time: "09:00",
    duration: "60 min",
    location: "Wellness Studio",
    spots: 3,
    intensity: "medium",
    price: "15€",
    category: "sports",
    joined: false,
  ),
  ActivityModel(
    activityName: "Culinary events",
    time: "14:30",
    duration: "120 min",
    location: "Park",
    spots: 0,
    intensity: "medium",
    price: "5€",
    category: "food",
    joined: false,
  ),
  ActivityModel(
    activityName: "Athletics: Barcelona Marathon",
    time: "09:00",
    duration: "180 min",
    location: "Barcelona",
    spots: 49,
    intensity: "high",
    price: "free",
    category: "sports",
    joined: false,
  ),
  ActivityModel(
    activityName: "5-a-side Football",
    time: "16:00",
    duration: "60 min",
    location: "Municipal Sports Center",
    spots: 4,
    intensity: "high",
    price: "13€",
    category: "kids",
    joined: false,
  ),
  ActivityModel(
    activityName: "Kids LEGO Club",
    time: "15:00",
    duration: "Drop-in until 20:00",
    location: "Municipal Sports Center",
    spots: 7,
    intensity: "light",
    price: "10€/hour",
    category: "kids",
    joined: false,
  ),
];
